### ISSUE TITLE
Restic repository : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Stolr** [vmware-tanzu/velero#2284]
Hi

I install velero from scratch using 1.2.0.

```
velero install \
    --provider aws \
    --bucket velero \
    --use-restic \
    --secret-file ./credentials-velero  \
    --use-volume-snapshots=false \
    --plugins  velero/velero-plugin-for-aws:v1.0.0 \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://oca-miniolb.oca.local/ 
```
```
velero version
Client:
	Version: v1.2.0
	Git commit: 5d008491bbf681658d3e372da1a9d3a21ca4c03c
Server:
	Version: v1.2.0
```

When I try to backup My  Gitlab instance : 

```
velero backup create tools-b-gitlab-backup-pr-20202002 --include-namespaces=ok106-gitlab-pr  --ttl 168h0m0s
Backup request "tools-b-gitlab-backup-pr-20202002" submitted successfully.
Run `velero backup describe tools-b-gitlab-backup-pr-20202002` or `velero backup logs tools-b-gitlab-backup-pr-20202002` for more details.
```

```
velero backup logs tools-b-gitlab-backup-pr-20202002 | grep error
time="2020-02-20T10:15:23Z" level=info msg="1 errors encountered backup up item" backup=velero/tools-b-gitlab-backup-pr-20202002 group=v1 logSource="pkg/backup/resource_backupper.go:284" name=gitlab-85cb89847d-zsp2r namespace=ok106-gitlab-pr resource=pods
time="2020-02-20T10:15:23Z" level=error msg="Error backing up item" backup=velero/tools-b-gitlab-backup-pr-20202002 error="restic repository is not ready: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=gitlab-85cb89847d-zsp2r namespace=ok106-gitlab-pr resource=pods
time="2020-02-20T10:15:23Z" level=info msg="1 errors encountered backup up item" backup=velero/tools-b-gitlab-backup-pr-20202002 group=v1 logSource="pkg/backup/resource_backupper.go:284" name=gitlab-db-postgres-85577bc49d-98v79 namespace=ok106-gitlab-pr resource=pods
time="2020-02-20T10:15:23Z" level=error msg="Error backing up item" backup=velero/tools-b-gitlab-backup-pr-20202002 error="restic repository is not ready: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=gitlab-db-postgres-85577bc49d-98v79 namespace=ok106-gitlab-pr resource=pods
time="2020-02-20T10:15:23Z" level=info msg="1 errors encountered backup up item" backup=velero/tools-b-gitlab-backup-pr-20202002 group=v1 logSource="pkg/backup/resource_backupper.go:284" name=gitlab-runner-5d46d75cb9-ckpn5 namespace=ok106-gitlab-pr resource=pods
time="2020-02-20T10:15:23Z" level=error msg="Error backing up item" backup=velero/tools-b-gitlab-backup-pr-20202002 error="restic repository is not ready: " error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/repository_ensurer.go:144" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*repositoryEnsurer).EnsureRepo" group=v1 logSource="pkg/backup/resource_backupper.go:288" name=gitlab-runner-5d46d75cb9-ckpn5 namespace=ok106-gitlab-pr resource=pods
```

So when I try to get restic repository 

```
elero restic repo get
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x147360b]

goroutine 1 [running]:
github.com/vmware-tanzu/velero/pkg/cmd/util/output.printResticRepo(0xc000091c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware-tanzu/velero/pkg/cmd/util/output/restic_repo_printer.go:60 +0x9b
github.com/vmware-tanzu/velero/pkg/cmd/util/output.printResticRepoList(0xc0000cd810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware-tanzu/velero/pkg/cmd/util/output/restic_repo_printer.go:41 +0x19a
reflect.Value.call(0x1784d80, 0x1a70318, 0x13, 0x19b8efa, 0x4, 0xc0006f5628, 0x2, 0x2, 0xc0006f56e8, 0xc000491c00, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x1784d80, 0x1a70318, 0x13, 0xc0006f5628, 0x2, 0x2, 0x1cd4e20, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/vmware-tanzu/velero/vendor/k8s.io/kubernetes/pkg/printers.printRowsForHandlerEntry(0x1cbc8c0, 0xc000124b40, 0xc000196410, 0x1cd4e20, 0xc0000cd810, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware-tanzu/velero/vendor/k8s.io/kubernetes/pkg/printers/tableprinter.go:288 +0x240
github.com/vmware-tanzu/velero/vendor/k8s.io/kubernetes/pkg/printers.(*HumanReadablePrinter).PrintObj(0xc0003976b0, 0x1cd4e20, 0xc0000cd810, 0x1cbc8c0, 0xc000124b40, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/vendor/k8s.io/kubernetes/pkg/printers/tableprinter.go:114 +0x500
github.com/vmware-tanzu/velero/pkg/cmd/util/output.printTable(0xc00001b180, 0x1cd4e20, 0xc0000cd810, 0x19ba5fc, 0x5, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/cmd/util/output/output.go:163 +0x443
github.com/vmware-tanzu/velero/pkg/cmd/util/output.PrintWithFormat(0xc00001b180, 0x1cd4e20, 0xc0000cd810, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/cmd/util/output/output.go:113 +0x181
github.com/vmware-tanzu/velero/pkg/cmd/cli/restic/repo.NewGetCommand.func1(0xc00001b180, 0x2ceb778, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/cmd/cli/restic/repo/get.go:55 +0x2e5
github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra.(*Command).execute(0xc00001b180, 0x2ceb778, 0x0, 0x0, 0xc00001b180, 0x2ceb778)
	/go/src/github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000164c80, 0x6, 0xc000164c80, 0x6)
	/go/src/github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/vmware-tanzu/velero/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/vmware-tanzu/velero/cmd/velero/main.go:34 +0x8a
```

Do you have any idea on how I could debug this ?

Thanks

**Comment by Stolr** [comment]
OK , 

Sorry it is ok now. Don't know what happend. Maybe a timeout or something. I didn't change anything and it started to work
