### ISSUE TITLE
 Velero v1.7 fails to start with CSI v0.2.0 plugin

### ISSUE THREAD

**Issue by joachimm** [vmware-tanzu/velero#4260]
**What steps did you take and what happened:**
I am running Velero on Azure Kubernetes Service, Managed from Argo-CD, using the official helm-charts,
 I wanted to update my test-environment using the helm chart. 

     2.23.8 -> 2.24.0 Which bumps Velero 1.6.3 -> 1.7.0

According to the compatibility guides I also need to update the two plugins I use:      

    velero-plugin-for-microsoft-azure:  v1.2.0 -> v1.3.0
    velero-plugin-for-csi: v0.1.2 -> v0.2.0

Unfortunately the Velero pod fails to start after this update.
Downgrading the csi plugin but keeping the other updates seems to at least make the pod startup again.
**What did you expect to happen:**
I expected the Velero pod to start up, and perform like previously.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

- `kubectl logs deployment/velero -n velero`
```time="2021-10-20T07:47:48Z" level=debug msg="looking for plugin in registry" backup=a-backup1 controller=backup-deletion kind=ObjectStore logSource="pkg/plugin/clientmgmt/manager.go:105" name=velero.io/csi-volumesnapshot-delete namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="creating new restartable plugin process" backup=a-backup1 command=/plugins/velero-plugin-for-csi controller=backup-deletion kind=ObjectStore logSource="pkg/plugin/clientmgmt/manager.go:120" name=velero.io/csi-volumesnapshot-delete namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="starting plugin" args="[/plugins/velero-plugin-for-csi --log-level debug --features EnableCSI]" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero path=/plugins/velero-plugin-for-csi
time="2021-10-20T07:47:48Z" level=debug msg="plugin started" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero path=/plugins/velero-plugin-for-csi pid=215
time="2021-10-20T07:47:48Z" level=debug msg="waiting for RPC address" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero path=/plugins/velero-plugin-for-csi
time="2021-10-20T07:47:48Z" level=debug msg="Setting log level to DEBUG" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="/go/pkg/mod/github.com/vmware-tanzu/velero@v1.6.2/pkg/plugin/framework/server.go:199" name=a-backup1-n262t namespace=velero pluginName=velero-plugin-for-csi
time="2021-10-20T07:47:48Z" level=debug msg="plugin address" address=/tmp/plugin964223084 backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero network=unix pluginName=velero-plugin-for-csi
time="2021-10-20T07:47:48Z" level=debug msg="using plugin" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero version=2
time="2021-10-20T07:47:48Z" level=debug msg="looking for plugin in registry" backup=a-backup1 controller=backup-deletion kind=ObjectStore logSource="pkg/plugin/clientmgmt/manager.go:105" name=velero.io/csi-volumesnapshotcontent-delete namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="found preexisting restartable plugin process" backup=a-backup1 command=/plugins/velero-plugin-for-csi controller=backup-deletion kind=ObjectStore logSource="pkg/plugin/clientmgmt/manager.go:116" name=velero.io/csi-volumesnapshotcontent-delete namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="2 actions before invoking actions" backup=a-backup1 controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:298" name=a-backup1-n262t namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="plugin process exited" backup=a-backup1 cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero path=/plugins/velero-plugin-for-microsoft-azure pid=207
time="2021-10-20T07:47:48Z" level=debug msg="plugin exited" backup=a-backup1 cmd=/plugins/velero-plugin-for-microsoft-azure controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero
time="2021-10-20T07:47:48Z" level=debug msg="plugin process exited" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero path=/plugins/velero-plugin-for-csi pid=215
time="2021-10-20T07:47:48Z" level=debug msg="plugin exited" backup=a-backup1 cmd=/plugins/velero-plugin-for-csi controller=backup-deletion logSource="pkg/plugin/clientmgmt/logrus_adapter.go:74" name=a-backup1-n262t namespace=velero
E1020 07:47:48.637353       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 835 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1e9cda0, 0x33158a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1e9cda0, 0x33158a0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile(0xc00090f484, 0x9, 0x0, 0x0, 0x24f9170, 0xc0003d2620, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:543 +0x61
github.com/vmware-tanzu/velero/pkg/controller.(*backupDeletionController).processRequest(0xc000521200, 0xc000e03ce0, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_deletion_controller.go:306 +0x28c5
github.com/vmware-tanzu/velero/pkg/controller.(*backupDeletionController).processQueueItem(0xc000521200, 0xc0008f2ac8, 0x16, 0xc00066fd70, 0x203000)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_deletion_controller.go:168 +0x27a
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc0003520c0, 0x203000)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:132 +0xf7
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(...)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:119
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000760fa0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000eb5fa0, 0x2486b60, 0xc000c920f0, 0xc00056ab01, 0xc000a1f200)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000760fa0, 0x3b9aca00, 0x0, 0x442401, 0xc000a1f200)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2(0xc0003520c0, 0x24cdcf8, 0xc00056ab80, 0xc0000f1060)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:92 +0x85
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:91 +0x1f7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1bb10c1]

goroutine 835 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1e9cda0, 0x33158a0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/vmware-tanzu/velero/pkg/controller.downloadToTempFile(0xc00090f484, 0x9, 0x0, 0x0, 0x24f9170, 0xc0003d2620, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/restore_controller.go:543 +0x61
github.com/vmware-tanzu/velero/pkg/controller.(*backupDeletionController).processRequest(0xc000521200, 0xc000e03ce0, 0x0, 0x0)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_deletion_controller.go:306 +0x28c5
github.com/vmware-tanzu/velero/pkg/controller.(*backupDeletionController).processQueueItem(0xc000521200, 0xc0008f2ac8, 0x16, 0xc00066fd70, 0x203000)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_deletion_controller.go:168 +0x27a
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc0003520c0, 0x203000)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:132 +0xf7
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(...)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:119
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000760fa0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000eb5fa0, 0x2486b60, 0xc000c920f0, 0xc00056ab01, 0xc000a1f200)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000760fa0, 0x3b9aca00, 0x0, 0x442401, 0xc000a1f200)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.9/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2(0xc0003520c0, 0x24cdcf8, 0xc00056ab80, 0xc0000f1060)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:92 +0x85
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:91 +0x1f7
```
Since the above log mentions  `a-backup1` I use that as `<backupname>` below
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```$> velero backup describe a-backup1 # I am using a-backup1 since it is mentioned in the logs
Name:         a-backup1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  Deleting

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        persistentvolumes
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-09-16 12:48:50 +0200 CEST
Completed:  <n/a>

Expiration:  2021-10-16 12:48:50 +0200 CEST

Velero-Native Snapshots: <none included>

Deletion Attempts:
  2021-10-19 15:23:02 +0200 CEST: InProgress

CSI Volume Snapshots: <none included>
```
- `velero backup logs <backupname>`
```Logs for backup "a-backup1" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.```

**Anything else you would like to add:**
`velero backup get` suggest I have some backups in status DELETING since a few days prior to when I started the upgrade process. According to the log above my upgrade try was started at 2021-10-20T07:47:48Z

```
    a-backup1                                              Deleting     0        0          2021-09-16 12:48:50 +0200 CEST   3d ago    default            <none>
```

**Environment:**

- Velero version (use `velero version`): v1.7.0
- Velero features (use `velero client config get features`): features: EnableCSI
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"0b17c6315e806a66d507e77760a5d60ab5cccfd8", GitTreeState:"clean", BuildDate:"2021-08-30T01:42:22Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: AKS
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by joachimm** [comment]
Is this what you need?
```
$> velero backup-location get
NAME         PROVIDER          BUCKET/PREFIX   PHASE       LAST VALIDATED                   ACCESS MODE   DEFAULT
azure-blob   velero.io/azure   velero-backup   Available   2021-10-20 16:19:39 +0200 CEST   ReadWrite     
default      azure             blubb           Unknown     Unknown                          ReadWrite     true
```
