### ISSUE TITLE
stacktrace is lost when panic happens in "ChangeStorageClassRestoreItemAction"

### ISSUE THREAD

**Issue by reasonerjt** [vmware-tanzu/velero#4815]
This is an issue discovered in #4782 , there's a nil pointer happened during the execution of the plugin but the stack trace is not printed in the log for some reason.

We need to double-check if the `handlePanic` works as expected:
https://github.com/vmware-tanzu/velero/blob/7b0d8217de62b960aadf620aba38e01e18849f8d/pkg/plugin/framework/handle_panic.go#L32

**Comment by reasonerjt** [comment]
For runtime errors it does not implement the interface [stackTracer]  (https://github.com/vmware-tanzu/velero/blob/release-1.9/pkg/plugin/framework/server_errors.go#L83)
For the best effort, we should probably dump the current stack trace as the plugin runs in the same go routine.

If I manually create a nil pointer the log would look like

`
time="2022-07-11T01:39:11+08:00" level=error msg="Error backing up item" backup=velero/nginx-snapshot-test-npe-9 error="error executing custom action (groupResource=persistentvolumeclaims, namespace=nginx-example, name=nginx-logs): rpc error: code = Aborted desc = plugin panicked: runtime error: invalid memory address or nil pointer dereference, stack trace: goroutine 479 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x7a\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework.handlePanic({0x33c1080, 0x48cae70})\n\t/Users/jiangd/velero-ws/velero/pkg/plugin/framework/handle_panic.go:43 +0x116\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework.(*BackupItemActionGRPCServer).Execute.func1()\n\t/Users/jiangd/velero-ws/velero/pkg/plugin/framework/backup_item_action_server.go:81 +0x3f\npanic({0x33c1080, 0x48cae70})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x262\ngithub.com/vmware-tanzu/velero/pkg/backup.(*PVCAction).Execute(0xc000a37470, {0x3933c40, 0xc0004ea040}, 0xc000436000)\n\t/Users/jiangd/velero-ws/velero/pkg/backup/backup_pv_action.go:56 +0x26f\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework.(*BackupItemActionGRPCServer).Execute(0xc000112a48, {0x390f338, 0xc000886f00}, 0xc000a0a3c0)\n\t/Users/jiangd/velero-ws/velero/pkg/plugin/framework/backup_item_action_server.go:101 +0x533\ngithub.com/vmware-tanzu/velero/pkg/plugin/generated._BackupItemAction_Execute_Handler({0x3412f00, 0xc000112a48}, {0x390f338, 0xc000886f00}, 0xc0003a00c0, 0x0)\n\t/Users/jiangd/velero-ws/velero/pkg/plugin/generated/BackupItemAction.pb.go:271 +0x385\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0001776c0, {0x3940958, 0xc0004fc000}, 0xc00044a120, 0xc000b81cb0, 0x48d2858, 0x0)\n\t/Users/jiangd/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x14c9\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0001776c0, {0x3940958, 0xc0004fc000}, 0xc00044a120, 0x0)\n\t/Users/jiangd/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0x85e\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2()\n\t/Users/jiangd/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x11d\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/Users/jiangd/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x345\n" logSource="/Users/jiangd/velero-ws/velero/pkg/backup/backup.go:417" name=nginx-deployment-66689547d-6smsw
`

It does not look pretty but contains sufficient information to help us debug where the problem is.
In this case it happens in `velero/pkg/backup/backup_pv_action.go:56`
