### ISSUE TITLE
segmetation fault when running velero backup create

### ISSUE THREAD

**Issue by georgekuruvillak** [vmware-tanzu/velero#5058]
**What steps did you take and what happened:**
I tried to run `velero backup create test --include-namespaces prophecy -o yaml` but resulted in segmentation fault as shown below:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x101119c]

goroutine 1 [running]:
reflect.mapiternext(0xc0002dc990?)
	runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x4640108?)
	github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000ba1620, 0xc000439970, 0xc000e06900)
	github.com/json-iterator/go@v1.1.11/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x28073e0?, 0xc000720801?, 0xc000e06918?)
	github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0009697d0, 0x270c0b6?, 0xc000e06900)
	github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc000969950, 0x1015501?, 0xc000e06900)
	github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000552000, 0x264de65?, 0xc000e06900)
	github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc0005520f0, 0x0?, 0xc000e06900)
	github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0002837c0?, 0x0?, 0x0?)
	github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0008f70f0, 0xc0004398c0, 0xc000ba0e70?)
	github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc000e06900, {0x2a677c0, 0xc0004398c0})
	github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0002837c0, {0x2a677c0, 0xc0004398c0})
	github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x2abb249?, {0x2e0b060?, 0xc0004398c0?}, {0x2e03180, 0xc000ba0e10})
	k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc0004bb9f0, {0x2e0b060, 0xc0004398c0}, {0x2e03180, 0xc000ba0e10})
	k8s.io/apimachinery@v0.22.2/pkg/runtime/serializer/json/json.go:301 +0xfc
github.com/vmware-tanzu/velero/pkg/util/encode.EncodeTo({0x2e0b060, 0xc0004398c0}, {0x7ffeefbff87b?, 0x2a677c0?}, {0x2e03180, 0xc000ba0e10})
	github.com/vmware-tanzu/velero/pkg/util/encode/encode.go:50 +0x6e
github.com/vmware-tanzu/velero/pkg/util/encode.Encode({0x2e0b060, 0xc0004398c0}, {0x7ffeefbff87b, 0x4})
	github.com/vmware-tanzu/velero/pkg/util/encode/encode.go:36 +0x65
github.com/vmware-tanzu/velero/pkg/cmd/util/output.printEncoded({0x2e0b060, 0xc0004398c0}, {0x7ffeefbff87b, 0x4})
	github.com/vmware-tanzu/velero/pkg/cmd/util/output/output.go:135 +0x7b
github.com/vmware-tanzu/velero/pkg/cmd/util/output.PrintWithFormat(0xc000aaa7e0?, {0x2e0b060, 0xc0004398c0})
	github.com/vmware-tanzu/velero/pkg/cmd/util/output/output.go:117 +0x74
github.com/vmware-tanzu/velero/pkg/cmd/cli/backup.(*CreateOptions).Run(0xc000aaa7e0, 0x0?, {0x2e28728, 0xc0000c5380})
	github.com/vmware-tanzu/velero/pkg/cmd/cli/backup/create.go:207 +0xc5
github.com/vmware-tanzu/velero/pkg/cmd/cli/backup.NewCreateCommand.func1(0xc000ab9b80?, {0xc0000c6d20, 0x1, 0x5})
	github.com/vmware-tanzu/velero/pkg/cmd/cli/backup/create.go:54 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc000ab9b80, {0xc0000c6cd0, 0x5, 0x5})
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ab9680)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/vmware-tanzu/velero/cmd/velero/velero.go:34 +0x65
```

**What did you expect to happen:**
Generate a Velero backup CR

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.9.0
	Git commit: -
Server:
	Version: v1.9.0
```

- Velero features (use `velero client config get features`): 
```
features: <NOT SET>
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher", GitCommit:"766e62361387c284022a97270f0997d67ae792d0", GitTreeState:"clean", BuildDate:"2020-12-01T16:16:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
```
EKS
```
- Cloud provider or hardware configuration: 
```
AWS 
```
- OS (e.g. from `/etc/os-release`):
```
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by georgekuruvillak** [comment]
Installed from tar file instead of brew and it worked fine.
