### ISSUE TITLE
Velero not updating the snapshot timeout feature available with  v1.9.1 version

### ISSUE THREAD

**Issue by bhargavkeshav** [vmware-tanzu/velero#5244]
**What steps did you take and what happened:**
We have deployed velero inside the EKS cluster using helm to take the backup of the applications. We are using AWS EBS CSI driver for the persistence volume storage.

Velero version: v1.9.1
EKS version: 1.20
plugins details:

```
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.5.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.3.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
```

We are taking daily backup of the all the application namespace using the schedule and its failing to take the snapshot of the volume.

Error:
```
time="2022-08-24T06:23:27Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=mission-control, name=velero-elasticsearch-data-mission-control-1-zplvr): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:417" name=mission-control-1
```

We have updated the timeout - `csiSnapshotTimeout: 60m` to avoid the failure but velero is not able to pick this updated timeout.

One more thing we noticed is velero pod is restarting during the failure of backup.

**What did you expect to happen:**

Velero should retry till 60min and take the backup of the volume before it fails. Currently its failing after 10min.

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

[bundle-2022-08-24-14-49-34.tar.gz](https://github.com/vmware-tanzu/velero/files/9414768/bundle-2022-08-24-14-49-34.tar.gz)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Other details :

```
MacBookPro-bhargavn:ops-namer bhargav$ velero create backup test-backup --from-schedule velero-utilities-backup
INFO[0005] No Schedule.template.metadata.labels set - using Schedule.labels for backup object  backup=velero/test-backup labels="map[app.kubernetes.io/instance:velero app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:velero helm.sh/chart:velero-2.31.3]"
Creating backup from schedule, all other filters are ignored.
Backup request "test-backup" submitted successfully.
Run `velero backup describe test-backup` or `velero backup logs test-backup` for more details.


schedule yaml which we are using.

MacBookPro-bhargavn:ops-namer bhargav$ kubectl get schedule -n velero -o yaml
+ kubectl get schedule -n velero -o yaml
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: Schedule
  metadata:
    annotations:
      helm.sh/hook: post-install,post-upgrade,post-rollback
      helm.sh/hook-delete-policy: before-hook-creation
    creationTimestamp: "2022-08-22T07:15:37Z"
    generation: 4
    labels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-2.31.3
    name: velero-utilities-backup
    namespace: velero
    resourceVersion: "346185824"
    uid: 0e939ebd-c71b-424d-abea-a2de7a8e3387
  spec:
    schedule: 0 3 * * *
    template:
      csiSnapshotTimeout: 60m
      includedNamespaces:
      - ********
      - mission-control
      - ********
      ttl: 240h
  status:
    lastBackup: "2022-08-24T03:00:27Z"
    phase: Enabled
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""


  Before taking backup - Pod status:

+ kubectl get pods
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
NAME                     READY   STATUS    RESTARTS   AGE
velero-856875585-56zg5   1/1     Running   0          20s
```

backup describe:

```
MacBookPro-bhargavn:ops-namer bhargav$ velero describe backup test-backup
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
Name:         test-backup
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.31.3
              velero.io/schedule-name=velero-utilities-backup
              velero.io/storage-location=default
Annotations:  helm.sh/hook=post-install,post-upgrade,post-rollback
              helm.sh/hook-delete-policy=before-hook-creation
              velero.io/source-cluster-k8s-gitversion=v1.20.15-eks-84b4fe6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20+

Phase:  Failed (run `velero backup logs test-backup` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  ********, mission-control, *******
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  240h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-08-24 11:24:50 +0530 IST
Completed:  2022-08-24 12:27:35 +0530 IST

Expiration:  2022-09-03 11:24:50 +0530 IST

Total items to be backed up:  1991
Items backed up:              1991

Velero-Native Snapshots: <none included>
```

pod logs before failure:

```
MacBookPro-bhargavn:ops-namer bhargav$ kubectl logs velero-856875585-56zg5 --previous | grep velero-elasticsearch-data-mission-control-1-zplvr
+ kubectl logs velero-856875585-56zg5 --previous
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
time="2022-08-24T06:13:27Z" level=info msg="Created volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/pvc_action.go:135" pluginName=velero-plugin-for-csi
time="2022-08-24T06:13:27Z" level=info msg="Backing up item" backup=velero/test-backup logSource="pkg/backup/item_backupper.go:123" name=velero-elasticsearch-data-mission-control-1-zplvr namespace=mission-control resource=volumesnapshots.snapshot.storage.k8s.io
time="2022-08-24T06:13:27Z" level=info msg="Executing custom action" backup=velero/test-backup logSource="pkg/backup/item_backupper.go:312" name=velero-elasticsearch-data-mission-control-1-zplvr namespace=mission-control resource=volumesnapshots.snapshot.storage.k8s.io
time="2022-08-24T06:13:27Z" level=info msg="Getting VolumesnapshotContent for Volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/backup/volumesnapshot_action.go:91" pluginName=velero-plugin-for-csi
time="2022-08-24T06:13:27Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr. Retrying in 5s" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi 
.
.
.
time="2022-08-24T06:23:27Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr. Retrying in 5s" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-24T06:23:27Z" level=info msg="Waiting for CSI driver to reconcile volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr. Retrying in 5s" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:169" pluginName=velero-plugin-for-csi
time="2022-08-24T06:23:27Z" level=error msg="Timed out awaiting reconciliation of volumesnapshot mission-control/velero-elasticsearch-data-mission-control-1-zplvr" backup=velero/test-backup cmd=/plugins/velero-plugin-for-csi logSource="/go/src/velero-plugin-for-csi/internal/util/util.go:191" pluginName=velero-plugin-for-csi
time="2022-08-24T06:23:27Z" level=error msg="Error backing up item" backup=velero/test-backup error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=mission-control, name=velero-elasticsearch-data-mission-control-1-zplvr): rpc error: code = Unknown desc = timed out waiting for the condition" logSource="pkg/backup/backup.go:417" name=mission-control-1

```

Volume snapshot and volume snapshot content created:

```
MacBookPro-bhargavn:ops-namer bhargav$ kubectl get volumesnapshot -n mission-control | grep velero-elasticsearch-data-mission-control-1-zplvr
+ kubectl get volumesnapshot -n mission-control
velero-elasticsearch-data-mission-control-1-zplvr     true         elasticsearch-data-mission-control-1                                                               100Gi         ebs-csi-snapclass   snapcontent-9a015c8c-ceea-4f42-ac4a-0667e743d95d          145m           158m


MacBookPro-bhargavn:ops-namer bhargav$ kubectl get volumesnapshotcontent -n mission-control | grep velero-elasticsearch-data-mission-control-1-zplvr
+ kubectl get volumesnapshotcontent -n mission-control
snapcontent-9a015c8c-ceea-4f42-ac4a-0667e743d95d          true         107374182400   Delete           ebs.csi.aws.com   ebs-csi-snapclass     velero-elasticsearch-data-mission-control-1-zplvr                 145m
```

**Environment:**

- Velero version (use `velero version`): v.1.9.1
- Velero features (use `velero client config get features`): csiSnapshotTimeout
- Kubernetes version (use `kubectl version`): 1.20
- Kubernetes installer & version: 1.20
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Its deployed using official helm 

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
@bhargavkeshav 
What is the size of volume you are backing up with? I supposed big size volume may take much time during moving snapshot data into object storage. but this is a little surprising to me the snapshot creation took more than ten minutes.  Is this a normal case for EKS snapshot creation?

Could you post more Velero pod log before failure? Need to check what is the reason of Velero pod restart.

**Comment by blackpiglet** [comment]
Checked with CSI external-snapshotter and AWS-EBS-CSI-driver code, external-snapshotter updates the VolumeSnapshotContent status snapshot handle immediately after CSI driver response CreateSnapshot RPC call. CSI driver CreateSnapshot calls EC2 [CreateSnapshot](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html) API.

This API  document doesn't illustrate when the API call will be returned and what's the timeout setting, but according to its response format, I think it should be an asyncronized call.

**Comment by bhargavkeshav** [comment]
@blackpiglet  We are running daily scheduled backup and it failing with same error everyday. When I checked the logs it failed for 4 volumes.

After everyday backup failure velero pod is restarting.
```
MacBookPro-bhargavn:is-perfeval bhargav$ kubectl get pods -n velero
+ kubectl get pods -n velero
NAME                     READY   STATUS    RESTARTS   AGE
velero-856875585-7drm2   1/1     Running   3          3d4h
```

Previous pod logs:

[velero.txt](https://github.com/vmware-tanzu/velero/files/9439527/velero.txt)

**Comment by blackpiglet** [comment]
@bhargavkeshav 
What is the size of the PVCs that failed in backup?
Also need to check the snapshot-controller, csi-snapshotter and AWS-EBS-CSI-driver's version.
I think I need to reproduce this case for debugging. Appreciate for more information of this case.

**Comment by bhargavkeshav** [comment]
The size of the PVCs that failed in backup.
```
mission-control-data-mission-control-0   Bound    pvc-d8391178-cf5c-4b55-ba10-e65b5f74a1ef   100Gi      RWO            aws-ebs-csi-sc   147d
mission-control-data-mission-control-1   Bound    pvc-2d25df72-0a6b-4d31-8c12-608e69053e42   100Gi      RWO            aws-ebs-csi-sc   147d
mission-control-data-mission-control-2   Bound    pvc-b5d29c08-11a0-47e0-bc88-7a953027bf3e   100Gi      RWO            aws-ebs-csi-sc   147d
```

Version details:

k8s.gcr.io/sig-storage/snapshot-controller:v4.0.0
602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.5.1
 k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
  k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
   k8s.gcr.io/sig-storage/csi-resizer:v1.1.0

**Comment by blackpiglet** [comment]
I created two PV with about 500GB data for testing, but I didn't meet the problem described.
The CSI environemnt is a little different from your configuration.
There is a CSI plugin v0.3.0 verified environment section in this place: https://github.com/vmware-tanzu/velero-plugin-for-csi#verified-environment
Could you please try to use new version of CSI snapshotter to see whether it works?

**Comment by reasonerjt** [comment]
Removing it from v1.9.2 candidate as this looks like an env specific problem,  we will re-evaulate once we have more information.

**Comment by bhargavkeshav** [comment]
@blackpiglet I configured the environment as specified in the link https://github.com/vmware-tanzu/velero-plugin-for-csi#verified-environment

Helm deployments:

```
aws-ebs-csi-driver       	kube-system               	5       	2022-09-05 18:38:31.806995 +0530 IST   	deployed	aws-ebs-csi-driver-2.6.10         	1.6.2 

velero                   	velero                    	13      	2022-09-05 17:56:21.498407 +0530 IST   	deployed	velero-2.31.3                     	1.9.1
```

CSI snapshotter running with v6.0.1 version.

With this version I am not able to take backup - its completely failing.

```
MacBookPro-bhargavn:aws-ebs-csi-driver bhargav$ velero create backup test --from-schedule velero-velero-test-app-backup 
Creating backup from schedule, all other filters are ignored.
Backup request "test" submitted successfully.
Run `velero backup describe test` or `velero backup logs test` for more details.

MacBookPro-bhargavn:aws-ebs-csi-driver bhargav$ velero backup describe test
Name:         test
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              backupname=velero-test-app-backup
              helm.sh/chart=velero-2.31.3
              velero.io/schedule-name=velero-velero-test-app-backup
              velero.io/storage-location=default
Annotations:  backupname=velero-test-app-backup
              helm.sh/hook=post-install,post-upgrade,post-rollback
              helm.sh/hook-delete-policy=before-hook-creation
              velero.io/source-cluster-k8s-gitversion=v1.20.15-eks-18ef993
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20+

Phase:  Failed (run `velero backup logs test` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  velero-test-app
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  240h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-09-05 19:10:43 +0530 IST
Completed:  2022-09-05 19:11:12 +0530 IST

Expiration:  2022-09-15 19:10:43 +0530 IST

Total items to be backed up:  33
Items backed up:              33

Velero-Native Snapshots: <none included>

MacBookPro-bhargavn:aws-ebs-csi-driver bhargav$ velero backup logs test
An error occurred: file not found
```

Velero pods got restarted and there is nothing in k8s events(not due to OOM)

```
+ kubectl get events
LAST SEEN   TYPE     REASON    OBJECT                        MESSAGE
4m18s       Normal   Created   pod/velero-5588667fbc-ps86v   Created container velero
4m18s       Normal   Started   pod/velero-5588667fbc-ps86v   Started container velero
4m18s       Normal   Pulled    pod/velero-5588667fbc-ps86v   Container image "registry.docker.io/velero/velero:v1.9.1" already present on machine
+ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
velero-5588667fbc-ps86v   1/1     Running   4          79m
```

When I checked the previous pod logs I can see below details:

```
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-d3a597a0-4fd1-4490-92b3-bac684ee1e2e" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-b7b871f5-1bcb-4515-baba-3e9cc297f94d" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-b1a2983e-19a8-429f-8d3a-0f7ae676b2fb" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-0248034e-588f-4dec-9ff2-b1d843bacaf4" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-a0886ee7-f251-45be-b081-233c63c02f20" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-9d94fd39-37b1-4af6-8b8f-9bdf0c0a03b2" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
time="2022-09-05T13:41:02Z" level=debug msg="Patching VolumeSnapshotContent snapcontent-fd6dbfc5-111a-4128-a983-068c407d1581" backup=velero/test logSource="pkg/controller/backup_controller.go:953"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x19c6efa]

goroutine 5285 [running]:
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot.func1(0xc000b84488)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:943 +0xda
created by github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:936 +0xf7
```
