### ISSUE TITLE
error Timed out awaiting reconciliation of volumesnapshot

### ISSUE THREAD

**Issue by midhuns3343** [vmware-tanzu/velero#5438]
Backup is getting failed with the below error:

```
2022/10/12 12:06:16 error Timed out awaiting reconciliation of volumesnapshot kcloak-cidp-prod/velero-data-kcloak-cidp-prod-db-mysql-0-dsvxb                            
time="2022-10-12T12:06:16Z" level=error msg="fail to wait VolumeSnapshot change to Ready: timed out waiting for the condition" backup=velero/kcloak-cidp-prod-test logSource="pkg/controller/backup_controller.go:651"                                                                                                                          


panic: runtime error: invalid memory address or nil pointer dereference                                                                                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19c6f6d]
goroutine 7369 [running]:                                                                                                                                               
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot.func1(0xc00059a780)                                                                      
/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:940 +0xad                                                                            
created by github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot
/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:936 +0xf7

panic: runtime error: invalid memory address or nil pointer dereference                                                                                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19c6f6d]
goroutine 7367 [running]: 
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot.func1(0xc0033c08c0)                                   
/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:940 +0xad
created by github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot
/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:936 +0xf7
```

# velero version                                                                                                              
Client:                                                                                                                                                                        
 Version: v1.9.2                                                                                                                                                         
Git commit: 82a100981cc66d119cf9b1d121f45c5c9dcf99e1                                                                                                            
Server:                                                                                                                                                                        
 Version: v1.9.2

**Comment by sjoukedv** [comment]
I am experiencing the same issue: as soon as the volumesnapshots are reconciled it throws the memory error

```
2022/10/22 12:45:37  info Waiting for CSI driver to reconcile volumesnapshot <namespace>/<volume-name>. Retrying in 5s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19c6f6d]

goroutine 1793 [running]:
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot.func1(0xc0010bab40)
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:940 +0xad
created by github.com/vmware-tanzu/velero/pkg/controller.(*backupController).deleteVolumeSnapshot
	/go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:936 +0xf7
```

Version: 1.9.2
Plugins: velero/velero-plugin-for-aws:v1.5.1, velero/velero-plugin-for-csi:v0.3.1, digitalocean/velero-plugin:v1.1.0

**Comment by blackpiglet** [comment]
After #5388 is merged, I think this issue should be fixed too.

**Comment by dejwsz** [comment]
> After #5388 is merged, I think this issue should be fixed too.

so when a new version will be present? I have the same issue

**Comment by blackpiglet** [comment]
v1.9.3 should be released next week.

**Comment by blackpiglet** [comment]
Close for now. Feel free for reopen, if anthing unexpected is found.
