### ISSUE TITLE
Backup API Type Fail

### ISSUE THREAD

**Issue by meijianwei-hub** [vmware-tanzu/velero#6405]
**What steps did you take and what happened:**
velero version is 1.9.7, k8s version 1.24
When I use API type to backup namespace, there is no data  transported to minio bucket, but if I use velero CLI command to backup the same namespace it is running successfuly.

mysql backup API type as below:
![image](https://github.com/vmware-tanzu/velero/assets/61965296/7dac8004-0126-4e7b-8bb0-0db64c6bd9f1)

logs from velero:
![image](https://github.com/vmware-tanzu/velero/assets/61965296/2ed28028-6a99-48b2-ad92-46db152ac469)

From the backup screenshot the status is Completed backups are use velero CLI to backup, the Failed backup is use "Backup API Type"
![image](https://github.com/vmware-tanzu/velero/assets/61965296/4f54cc99-3c48-467a-a124-2b934ca80cf1)

logs from fail backup:
![image](https://github.com/vmware-tanzu/velero/assets/61965296/346939a0-044f-48f7-b3dd-6bfca23ea7a9)
![image](https://github.com/vmware-tanzu/velero/assets/61965296/3fc4b3d1-cf03-424a-b400-2867acc16aa8)
![image](https://github.com/vmware-tanzu/velero/assets/61965296/b3cd680f-08ee-4716-a82e-cecfcd2174ba)

There is no backup data in minio bucket， for the velero CLI backup，I can see the backup data as below screenshot:
![image](https://github.com/vmware-tanzu/velero/assets/61965296/118bb736-8a51-45c0-95dd-34b9ad56037a)
 
_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

_If you are using earlier versions:_  
Please provide the output of the following commands (Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
- `kubectl logs deployment/velero -n velero`
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
- `velero backup logs <backupname>`
- `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
- `velero restore logs <restorename>`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by ywk253100** [comment]
Could you check or provide the completed logs of the Velero pod?

**Comment by meijianwei-hub** [comment]
[bundle-2023-06-17-18-09-37.tar.gz](https://github.com/vmware-tanzu/velero/files/11783198/bundle-2023-06-17-18-09-37.tar.gz)
@ywk253100 the logs attached， I create a new backup use the same backup API type. the same phenomenon occurs， Please help me fix the issue，thanks very much.

**Comment by ywk253100** [comment]
I didn't find any related logs for the failed backup. Did the Velero crash or restart?

**Comment by meijianwei-hub** [comment]
Yes, I didn’t see any useful logs, velero has restarted, this is also what I find strange, using velero CLI the data can be synchronized to minio, but using the backup API type, the data is not synchronized to minio, And there is no relevant log prompt, is there something wrong with my backup API type configuration?
![image](https://github.com/vmware-tanzu/velero/assets/61965296/e58bf455-2d4c-4a25-a9ab-f4d74be13c72)

**Comment by ywk253100** [comment]
Seems the Velero crashed during the processing of the backup.
You can check the logs of the previous instance of velero by adding `-p` flag in the `kubectl logs` command.

**Comment by meijianwei-hub** [comment]
After adding -p flag, the logs of velero shown as below:

time="2023-06-17T10:32:50Z" level=info msg="Getting items for group" backup=velero/velero-hook-backup-new group=extensions/v1beta1 logSource="pkg/backup/item_collector.go:81"
time="2023-06-17T10:32:50Z" level=info msg="Getting items for resource" backup=velero/velero-hook-backup-new group=extensions/v1beta1 logSource="pkg/backup/item_collector.go:170" resource=ingresses
time="2023-06-17T10:32:50Z" level=info msg="Skipping resource because it's excluded" backup=velero/velero-hook-backup-new group=extensions/v1beta1 logSource="pkg/backup/item_collector.go:207" resource=ingresses
time="2023-06-17T10:32:50Z" level=info msg="Collected 0 items matching the backup spec from the Kubernetes API (actual number of items backed up may be more or less depending on velero.io/exclude-from-backup annotation, plugins returning additional related items to back up, etc.)" backup=velero/velero-hook-backup-new logSource="pkg/backup/backup.go:264" progress=
time="2023-06-17T10:32:50Z" level=info msg="Backed up a total of 0 items" backup=velero/velero-hook-backup-new logSource="pkg/backup/backup.go:405" progress=
E0617 10:32:50.147972       1 runtime.go:79] Observed a panic: &errors.errorString{s:"counter cannot decrease in value"} (counter cannot decrease in value)
goroutine 1244 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d8f060?, 0xc0008cb7d0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000f9bde0?})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d8f060, 0xc0008cb7d0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/prometheus/client_golang/prometheus.(*counter).Add(0x1db6040?, 0xc0008cb7c0?)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/counter.go:109 +0xf4
github.com/vmware-tanzu/velero/pkg/metrics.(*ServerMetrics).RegisterVolumeSnapshotFailures(0xc11b80d4888cd34b?, {0x0, 0x0}, 0xffffffffffffffff)
        /go/src/github.com/vmware-tanzu/velero/pkg/metrics/metrics.go:627 +0xc4
github.com/vmware-tanzu/velero/pkg/controller.recordBackupMetrics({0x2578970, 0xc000e6ea10}, 0xc000abf080, 0x9?, 0xc0004eb860?)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:751 +0x245
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup(0xc00023c8c0, 0xc000dd8820)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:697 +0x16bd
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup(0xc00023c8c0, {0xc000bb9640, 0x1d})
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:293 +0x75c
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc000ea2ae0)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:132 +0xeb
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(0xc000c54ea8?)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:119 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c54f82?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c54fd0?, {0x25457a0, 0xc0009a8ea0}, 0x1, 0xc00016cba0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f202d0?, 0x3b9aca00, 0x0, 0x65?, 0x0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2()
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:92 +0x6e
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:91 +0x45a
panic: counter cannot decrease in value [recovered]
        panic: counter cannot decrease in value

goroutine 1244 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000f9bde0?})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1d8f060, 0xc0008cb7d0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/prometheus/client_golang/prometheus.(*counter).Add(0x1db6040?, 0xc0008cb7c0?)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/counter.go:109 +0xf4
github.com/vmware-tanzu/velero/pkg/metrics.(*ServerMetrics).RegisterVolumeSnapshotFailures(0xc11b80d4888cd34b?, {0x0, 0x0}, 0xffffffffffffffff)
        /go/src/github.com/vmware-tanzu/velero/pkg/metrics/metrics.go:627 +0xc4
github.com/vmware-tanzu/velero/pkg/controller.recordBackupMetrics({0x2578970, 0xc000e6ea10}, 0xc000abf080, 0x9?, 0xc0004eb860?)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:751 +0x245
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).runBackup(0xc00023c8c0, 0xc000dd8820)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:697 +0x16bd
github.com/vmware-tanzu/velero/pkg/controller.(*backupController).processBackup(0xc00023c8c0, {0xc000bb9640, 0x1d})
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/backup_controller.go:293 +0x75c
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).processNextWorkItem(0xc000ea2ae0)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:132 +0xeb
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).runWorker(0xc000c54ea8?)
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:119 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c54f82?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c54fd0?, {0x25457a0, 0xc0009a8ea0}, 0x1, 0xc00016cba0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f202d0?, 0x3b9aca00, 0x0, 0x65?, 0x0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90
github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run.func2()
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:92 +0x6e
created by github.com/vmware-tanzu/velero/pkg/controller.(*genericController).Run
        /go/src/github.com/vmware-tanzu/velero/pkg/controller/generic_controller.go:91 +0x45a

**Comment by meijianwei-hub** [comment]
HI @ywk253100 
What other log information do I need to provide？
