### ISSUE TITLE
Unable to restore Load balancer.

### ISSUE THREAD

**Issue by Piklu-Das-85** [vmware-tanzu/velero#7502]
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.1.0
  Build:         cacbee86b6ccc45bde8ffc184521bed3022e7dee
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.9

-------------------------------------------------------------------------------

W0307 06:05:27.104172       7 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0307 06:05:27.104883       7 main.go:223] "Creating API client" host="https://172.20.0.1:443"
I0307 06:05:27.117686       7 main.go:267] "Running in Kubernetes cluster" major="1" minor="25+" git="v1.25.16-eks-77b1e4e" state="clean" commit="c39acac7636499dd73442b62e11951592aedd1f8" platform="linux/amd64"
F0307 06:05:27.122155       7 main.go:92] No service with name ingress-nginx-controller found in namespace isnp: services "ingress-nginx-controller" not found
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        k8s.io/klog/v2@v2.10.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x28a5ba0, 0x3, {0x0, 0x0}, 0xc0000f7960, 0x1, {0x1f83e62, 0x28a66e0}, 0xc00043dfa0, 0x0)
        k8s.io/klog/v2@v2.10.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printDepth(0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x444ed1, {0xc00043dfa0, 0x1, 0x1})
        k8s.io/klog/v2@v2.10.0/klog.go:735 +0x1ba
k8s.io/klog/v2.(*loggingT).print(...)
        k8s.io/klog/v2@v2.10.0/klog.go:717
k8s.io/klog/v2.Fatal(...)
        k8s.io/klog/v2@v2.10.0/klog.go:1494
main.main()
        k8s.io/ingress-nginx/cmd/nginx/main.go:92 +0x5ce

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
        k8s.io/klog/v2@v2.10.0/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
        k8s.io/klog/v2@v2.10.0/klog.go:420 +0xfb

goroutine 24 [runnable]:
golang.org/x/net/http2.(*clientConnReadLoop).handleResponse·dwrap·55()
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/transport.go:2051
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1
created by golang.org/x/net/http2.(*clientConnReadLoop).handleResponse
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/transport.go:2051 +0x638

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x7fa7110f56d8, 0x72)
        runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc000092200, 0xc000184a80, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000092200, {0xc000184a80, 0x94e, 0x94e})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000092200, {0xc000184a80, 0xc000184aca, 0xfa})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00033c218, {0xc000184a80, 0x3fffd2000fffe6, 0xc0001437f0})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00032a618, {0xc000184a80, 0x0, 0x409b6d})
        crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00003c5f8, {0x1b6e180, 0xc00032a618})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00003c380, {0x1b70800, 0xc00033c218}, 0x909)
        crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00003c380, 0x0)
        crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00003c380, {0xc0001d1000, 0x1000, 0xc0002c8420})
        crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0002c8240, {0xc0001b42d8, 0x9, 0xc000338ce0})
        bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1b6dfe0, 0xc0002c8240}, {0xc0001b42d8, 0x9, 0x9}, 0x9)
        io/io.go:328 +0x9a
io.ReadFull(...)
        io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc0001b42d8, 0x9, 0x28a66e0}, {0x1b6dfe0, 0xc0002c8240})
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001b42a0)
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/frame.go:492 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000143fa0)
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/transport.go:1816 +0x165
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000336000)
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/transport.go:1738 +0x79
created by golang.org/x/net/http2.(*Transport).newClientConn
        golang.org/x/net@v0.0.0-20210805182204-aaa1db679c0d/http2/transport.go:694 +0xb45

**Comment by Piklu-Das-85** [comment]
Below is the restore logs-

time="2024-03-07T05:48:44Z" level=info msg="Attempting to restore CustomResourceDefinition: ingressclassparams.elbv2.k8s.aws" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:44Z" level=info msg="the managed fields for ingressclassparams.elbv2.k8s.aws is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:44Z" level=info msg="Restored 10 items out of an estimated total of 19 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingressclassparams.elbv2.k8s.aws namespace= progress= resource=customresourcedefinitions.apiextensions.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:46Z" level=info msg="Resource 'ingressclasses.networking.k8s.io' will be restored at cluster scope" logSource="pkg/restore/restore.go:2266" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:46Z" level=info msg="Resource 'ingresses.networking.k8s.io' will be restored into namespace 'isnp'" logSource="pkg/restore/restore.go:2264" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:46Z" level=info msg="Skipping customresourcedefinitions.apiextensions.k8s.io/ingressclassparams.elbv2.k8s.aws because it's already been restored." logSource="pkg/restore/restore.go:1191" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:46Z" level=info msg="Restored 19 items out of an estimated total of 814 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingressclassparams.elbv2.k8s.aws namespace= progress= resource=customresourcedefinitions.apiextensions.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:47Z" level=info msg="Attempting to restore ServiceAccount: ingress-nginx" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:47Z" level=info msg="the managed fields for isnp/ingress-nginx is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:47Z" level=info msg="Restored 32 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx namespace=isnp progress= resource=serviceaccounts restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:57Z" level=info msg="Attempting to restore Secret: ingress-nginx-admission" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:57Z" level=info msg="the managed fields for isnp/ingress-nginx-admission is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:57Z" level=info msg="Restored 145 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-admission namespace=isnp progress= resource=secrets restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="Attempting to restore Secret: sh.helm.release.v1.ingress-nginx.v1" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="the managed fields for isnp/sh.helm.release.v1.ingress-nginx.v1 is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="Restored 159 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=sh.helm.release.v1.ingress-nginx.v1 namespace=isnp progress= resource=secrets restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="Attempting to restore Secret: sh.helm.release.v1.ingress-nginx.v2" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="the managed fields for isnp/sh.helm.release.v1.ingress-nginx.v2 is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:48:58Z" level=info msg="Restored 160 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=sh.helm.release.v1.ingress-nginx.v2 namespace=isnp progress= resource=secrets restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="Attempting to restore ConfigMap: ingress-controller-leader" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="the managed fields for isnp/ingress-controller-leader is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="Restored 201 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-controller-leader namespace=isnp progress= resource=configmaps restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="Attempting to restore ConfigMap: ingress-nginx-controller" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="the managed fields for isnp/ingress-nginx-controller is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:01Z" level=info msg="Restored 202 items out of an estimated total of 809 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller namespace=isnp progress= resource=configmaps restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:03Z" level=info msg="Pod isnp/ingress-nginx-controller-85df6bbff4-2x9h8 has no init.hook.restore.velero.io/container-image annotation, no initRestoreHook in annotation" cmd=/velero logSource="internal/hook/item_hook_handler.go:418" pluginName=velero restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:03Z" level=info msg="Returning pod isnp/ingress-nginx-controller-85df6bbff4-2x9h8 with 0 init container(s)" cmd=/velero logSource="internal/hook/item_hook_handler.go:184" pluginName=velero restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:03Z" level=info msg="Attempting to restore Pod: ingress-nginx-controller-85df6bbff4-2x9h8" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:03Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-85df6bbff4-2x9h8 is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:03Z" level=info msg="Restored 235 items out of an estimated total of 791 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-85df6bbff4-2x9h8 namespace=isnp progress= resource=pods restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:12Z" level=info msg="Attempting to restore ReplicaSet: ingress-nginx-controller-85df6bbff4" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:12Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-85df6bbff4 is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:12Z" level=info msg="Restored 282 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-85df6bbff4 namespace=isnp progress= resource=replicasets.apps restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Attempting to restore Endpoints: ingress-nginx-controller-admission" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-admission is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Restored 343 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-admission namespace=isnp progress= resource=endpoints restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Attempting to restore Endpoints: ingress-nginx-controller" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="the managed fields for isnp/ingress-nginx-controller is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Restored 344 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller namespace=isnp progress= resource=endpoints restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Attempting to restore Service: ingress-nginx-controller-admission" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-admission is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:24Z" level=info msg="Restored 360 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-admission namespace=isnp progress= resource=services restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:25Z" level=info msg="Attempting to restore ClusterRoleBinding: ingress-nginx" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:25Z" level=info msg="the managed fields for ingress-nginx is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:25Z" level=info msg="Restored 434 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx namespace= progress= resource=clusterrolebindings.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:26Z" level=info msg="Attempting to restore ClusterRole: ingress-nginx-external" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:26Z" level=info msg="the managed fields for ingress-nginx-external is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:26Z" level=info msg="Restored 512 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-external namespace= progress= resource=clusterroles.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:26Z" level=info msg="Attempting to restore ClusterRole: ingress-nginx-internal" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:27Z" level=info msg="the managed fields for ingress-nginx-internal is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:27Z" level=info msg="Restored 513 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-internal namespace= progress= resource=clusterroles.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:27Z" level=info msg="Attempting to restore ClusterRole: ingress-nginx" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:27Z" level=info msg="the managed fields for ingress-nginx is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:27Z" level=info msg="Restored 514 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx namespace= progress= resource=clusterroles.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:33Z" level=info msg="Attempting to restore Deployment: ingress-nginx-controller" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:33Z" level=info msg="the managed fields for isnp/ingress-nginx-controller is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:33Z" level=info msg="Restored 636 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller namespace=isnp progress= resource=deployments.apps restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Attempting to restore EndpointSlice: ingress-nginx-controller-67256" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-67256 is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Restored 641 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-67256 namespace=isnp progress= resource=endpointslices.discovery.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Attempting to restore EndpointSlice: ingress-nginx-controller-admission-bpxtm" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="the managed fields for isnp/ingress-nginx-controller-admission-bpxtm is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Restored 642 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-controller-admission-bpxtm namespace=isnp progress= resource=endpointslices.discovery.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Restored 674 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=nginx namespace= progress= resource=ingressclasses.networking.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:34Z" level=info msg="Restored 675 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=cpg-backend-cpg-backend-deploy namespace=isnp progress= resource=ingresses.networking.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:35Z" level=info msg="Restored 676 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=isnp-backend-isnp-backend-deploy namespace=isnp progress= resource=ingresses.networking.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:35Z" level=info msg="Restored 677 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=isnp-esp-backend-isnp-esp-backend-deploy namespace=isnp progress= resource=ingresses.networking.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:35Z" level=info msg="Restored 678 items out of an estimated total of 793 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=isnp-portal-backend-isnp-portal-backend-deploy namespace=isnp progress= resource=ingresses.networking.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:36Z" level=info msg="Attempting to restore RoleBinding: ingress-nginx" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:36Z" level=info msg="the managed fields for isnp/ingress-nginx is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:36Z" level=info msg="Restored 731 items out of an estimated total of 769 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx namespace=isnp progress= resource=rolebindings.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:37Z" level=info msg="Attempting to restore Role: ingress-nginx" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:37Z" level=info msg="the managed fields for isnp/ingress-nginx is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:37Z" level=info msg="Restored 734 items out of an estimated total of 769 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx namespace=isnp progress= resource=roles.rbac.authorization.k8s.io restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:38Z" level=info msg="Attempting to restore ValidatingWebhookConfiguration: ingress-nginx-admission" logSource="pkg/restore/restore.go:1513" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:38Z" level=info msg="the managed fields for ingress-nginx-admission is patched" logSource="pkg/restore/restore.go:1714" restore=velero/isnp-restore-07-03-2024-11-00
time="2024-03-07T05:49:38Z" level=info msg="Restored 757 items out of an estimated total of 769 (estimate will change throughout the restore)" logSource="pkg/restore/restore.go:807" name=ingress-nginx-admission namespace= progress= resource=validatingwebhookconfigurations.admissionregistration.k8s.io restore=velero/isnp-restore-07-03-2024-11-00

**Comment by Piklu-Das-85** [comment]
apiVersion: velero.io/v1
kind: Restore
metadata:
  creationTimestamp: "2024-03-07T05:48:43Z"
  finalizers:
  - restores.velero.io/external-resources-finalizer
  generation: 56
  managedFields:
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:backupName: {}
        f:hooks: {}
        f:includedNamespaces: {}
      f:status: {}
    manager: velero
    operation: Update
    time: "2024-03-07T05:48:43Z"
  - apiVersion: velero.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"restores.velero.io/external-resources-finalizer": {}
      f:spec:
        f:excludedResources: {}
        f:itemOperationTimeout: {}
      f:status:
        f:completionTimestamp: {}
        f:errors: {}
        f:hookStatus: {}
        f:phase: {}
        f:progress:
          .: {}
          f:itemsRestored: {}
          f:totalItems: {}
        f:startTimestamp: {}
        f:warnings: {}
    manager: velero-server
    operation: Update
    time: "2024-03-07T05:49:38Z"
  name: isnp-restore-07-03-2024-11-00
  namespace: velero
  resourceVersion: "5164"
  uid: 2ca0ac7e-2adc-49c5-b382-829a96b6ac07
spec:
  backupName: isnp-backup-07-03-2024-11-00
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  - csinodes.storage.k8s.io
  - volumeattachments.storage.k8s.io
  - backuprepositories.velero.io
  hooks: {}
  includedNamespaces:
  - '*'
status:
  completionTimestamp: "2024-03-07T05:49:38Z"
  errors: 5
  phase: PartiallyFailed
  startTimestamp: "2024-03-07T05:48:43Z"
  warnings: 278

**Comment by Piklu-Das-85** [comment]
Velero Versions- 
Client:
        Version: v1.5.4
        Git commit: 525705bceb8895b9da2cf2a1d1a79b99d74723cb
Server:
        Version: v1.13.0

**Comment by Piklu-Das-85** [comment]
velero/velero-plugin-for-aws:v1.9.0
kubernetes verion - 1.25

**Comment by allenxu404** [comment]
Can you share us with more detailed info to help better troubleshoot by running command `velero debug`? 

Based on the info above, it appears the restore processing is PartiallyFailed.

**Comment by reasonerjt** [comment]
Closing due to inactivity.
