### ISSUE TITLE
rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin1800396287: connect: connection refused\"

### ISSUE THREAD

**Issue by schwindp** [vmware-tanzu/velero#7647]
**What steps did you take and what happened:**

Backups running our hourly schedule failed twice repeatingly:

```
$ ~/velero-v1.12.2-linux-amd64/velero get backup|head -n 2
NAME                        STATUS            ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
nl-default-20240409085440   Failed            0        0          2024-04-09 10:54:40 +0200 CEST   6d        default            <none>
nl-default-20240409075439   Failed            0        0          2024-04-09 09:54:39 +0200 CEST   6d        default            <none>
```
```
$ velero describe backups nl-default-20240409085440
Name:         nl-default-20240409085440
Namespace:    nl-velero
Labels:       velero.io/schedule-name=nl-default
              velero.io/storage-location=default
Annotations:  velero.io/resource-timeout=10m0s
              velero.io/source-cluster-k8s-gitversion=v1.18.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Failed (run `velero backup logs nl-default-20240409085440` for more information)


Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto
Snapshot Move Data:          auto
Data Mover:                  velero

TTL:  168h0m0s

CSISnapshotTimeout:    10m0s
ItemOperationTimeout:  4h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2024-04-09 10:54:40 +0200 CEST
Completed:  <n/a>

Expiration:  2024-04-16 10:54:40 +0200 CEST

Total items to be backed up:  9064
Items backed up:              9064

Velero-Native Snapshots: <none included>
```

**What did you expect to happen:**
Backups running nice and smooth, listing themselves als "Completed".

**The following information will help us better understand what's going on**:

_If you are using velero v1.7.0+:_  
Please use `velero debug  --backup <backupname> --restore <restorename>` to generate the support bundle, and attach to this issue, more options please refer to `velero debug --help` 

**Anything else you would like to add:**
Backups failing eventually from time to time, about 10% are bad.

**Environment:**

- Velero version (use `velero version`): Client:
        Version: v1.12.2
        Git commit: 06d12dec4030703cb46b2699ca434cdabd9edbb0
Server:
        Version: v1.12.0-rc.1

- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): NOT SET
- Kubernetes installer & version: v1.18
- OS (e.g. from `/etc/os-release`): Debian 10
[bundle-2024-04-09-11-33-40.tar.gz](https://github.com/vmware-tanzu/velero/files/14916780/bundle-2024-04-09-11-33-40.tar.gz)

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by blackpiglet** [comment]
```
time="2024-04-05T14:54:41+08:00" level=error msg="Error backing up item" backup=velero/csi-merge-05 error="error executing custom action (groupResource=volumesnapshots.snapshot.storage.k8s.io, namespace=test, name=velero-my-pvc-hxz9f): rpc error: code = Aborted desc = plugin panicked: assignment to entry in nil map, stack trace: goroutine 181 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x64\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework/common.HandlePanic({0x105f506a0, 0x1063be1f0})\n\t/Users/jxun/go/src/github.com/vmware-tanzu/velero/pkg/plugin/framework/common/handle_panic.go:43 +0x108\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework/backupitemaction/v2.(*BackupItemActionGRPCServer).Execute.func1()\n\t/Users/jxun/go/src/github.com/vmware-tanzu/velero/pkg/plugin/framework/backupitemaction/v2/backup_item_action_server.go:90 +0x38\npanic({0x105f506a0?, 0x1063be1f0?})\n\t/usr/local/go/src/runtime/panic.go:920 +0x254\ngithub.com/vmware-tanzu/velero/pkg/backup/actions.(*volumeSnapshotBackupItemAction).Execute(0x14000b76300, {0x1063fd628, 0x14000420390}, 0x14000a87500)\n\t/Users/jxun/go/src/github.com/vmware-tanzu/velero/pkg/backup/actions/csi_volumesnapshot_action.go:188 +0x11a4\ngithub.com/vmware-tanzu/velero/pkg/plugin/framework/backupitemaction/v2.(*BackupItemActionGRPCServer).Execute(0x1400008d0f0, {0x1063f4438, 0x14000e00690}, 0x1400018aaf0)\n\t/Users/jxun/go/src/github.com/vmware-tanzu/velero/pkg/plugin/framework/backupitemaction/v2/backup_item_action_server.go:110 +0x38c\ngithub.com/vmware-tanzu/velero/pkg/plugin/generated/backupitemaction/v2._BackupItemAction_Execute_Handler({0x106100400, 0x1400008d0f0}, {0x1063f4438, 0x14000e00690}, 0x1400057f200, 0x0)\n\t/Users/jxun/go/src/github.com/vmware-tanzu/velero/pkg/plugin/generated/backupitemaction/v2/BackupItemAction.pb.go:794 +0x28c\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0x14000634200, {0x1063f4438, 0x14000e00600}, {0x106400338, 0x140003e0ea0}, 0x14000bb6fc0, 0x1400070f620, 0x1077f0c18, 0x0)\n\t/Users/jxun/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0x1360\ngoogle.golang.org/grpc.(*Server).handleStream(0x14000634200, {0x106400338, 0x140003e0ea0}, 0x14000bb6fc0)\n\t/Users/jxun/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0xd00\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\t/Users/jxun/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0xf4\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 31\n\t/Users/jxun/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x1c8\n" logSource="pkg/backup/backup.go:495" name=hello-app-db489598b-q5dcj
```

I think this error means you installed the latest Velero image in the environment. 
Please use the the released Velero version. Suggest you can try with the v1.12.3 or the v1.13.1.
